In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

### 다중 선형 회귀 Multi Variables Linear Regression

<img src="https://raw.githubusercontent.com/jaygil8755/ML01/master/02%20%EB%8B%A4%EC%A4%91%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80/multi_linear.png" width=600 height=400>

In [2]:
file_path ='https://raw.githubusercontent.com/jaygil8755/ML01/master/02%20%EB%8B%A4%EC%A4%91%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80/house_price.csv'
df = pd.read_csv(file_path)
df

area  rooms  age  price
0    40      3   10    550
1    30      3    1    540
2    24      3   20    300
3    18      2    2    280
4    40      4   15    500
5    33      3    1    500
6    24      3    8    280
7    20      2    8    240

In [3]:
df.columns

Index(['area', 'rooms', 'age', 'price'], dtype='object')

In [4]:
features = df.drop('price', axis=1)
label = df['price']

In [5]:
reg = linear_model.LinearRegression()
reg.fit(features,label)

LinearRegression()

In [6]:
reg.coef_

array([14.2995628 , 11.34462619, -6.99351704])

In [7]:
reg.intercept_

13.631540401670577

In [8]:
# 32평 방 3개 15년
reg.predict([[32, 3, 15]])

C:\Users\Jay\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([400.34867308])

In [9]:
# 경고 메시지 해결하기 

In [10]:
features.values

array([[40,  3, 10],
       [30,  3,  1],
       [24,  3, 20],
       [18,  2,  2],
       [40,  4, 15],
       [33,  3,  1],
       [24,  3,  8],
       [20,  2,  8]], dtype=int64)

In [11]:
reg = linear_model.LinearRegression()
reg.fit(features.values,label.values)

LinearRegression()

In [12]:
# 32평 방 3개 15년
reg.predict([[32, 3, 15]])

array([400.34867308])

In [13]:
reg.predict(np.array([[32, 3, 15]]))

array([400.34867308])

In [14]:
# 수식 검증

price = reg.coef_[0]*32 + reg.coef_[1]*3 + reg.coef_[2]*15 + reg.intercept_
price

400.34867307835566